# -*- coding: utf-8 -*-
"""Ass1ErosionDilationOpeningClosing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ep0tuuhULF5vz8VRk3h7FFWvmUCTYDEz
"""

# Perform Erosion, dilation, Opening, Closing on a gray level image using 4X2 kernel and show all inputs (RGB and gray image both) and outputs.
# Importing Image class from PIL module

import cv2 
from google.colab.patches import cv2_imshow
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

img = cv2.imread('thelionking.jpeg', cv2.IMREAD_GRAYSCALE)
_, mask = cv2.threshold(img, 200, 235, cv2.THRESH_BINARY_INV)

kernal = np.ones((4,2), np.uint8) #Using 4x2 Kernel

# Performing Erosion, dilation, Opening, Closing on a gray level image 

erosion = cv2.erode(mask, kernal, iterations=1)
dilation = cv2.dilate(mask, kernal, iterations=2)
opening = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernal)
closing = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernal)

titles = ['image', 'mask', 'erosion', 'dilation',  'opening', 'closing']
images = [img, mask, erosion, dilation,  opening, closing]

for i in range(6):
    plt.subplot(2, 3, i+1), plt.imshow(images[i], 'gray')
    plt.title(titles[i])
    plt.xticks([]),plt.yticks([])

plt.show()